export enum ActionType {
    GET_DASHBOARDTABLE_DATA="GET_DASHBOARDTABLE_DATA",
    GET_DASHBOARDTABLE_DATA_FAIL="GET_DASHBOARDTABLE_DATA_FAIL",
    GET_DASHBOARDTABLE_DATA_SUCCESS="GET_DASHBOARDTABLE_DATA_SUCCESS" 
}
